version: 2.1
workflows:
  test:
    jobs:
      - eslint
defaults:
  docker: &default
    working_directory: ~/builds
    docker:
      - image: cimg/node:16.14.2
jobs:
  eslint:
    <<: *default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run eslint
          command: npm run eslint
          environment:
            # Necessary to display all linted files and total time spent,
            # even if no issues found.
            DEBUG: eslint:cli-engine eslint
