version: 2.1
orbs:
  testlio: testlio/testlio@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  schedule-run-for-a-project:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Unzip Sample Test Project
          command: |
            unzip testlio-platform-automation-main.zip
      - testlio/install
      - testlio/create-run:
          dir: "testlio-platform-automation-main"
          token: ${RUN_API_TOKEN_STAGING}
workflows:
  test-deploy:
    jobs:
      - schedule-run-for-a-project:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: testlio/testlio
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - schedule-run-for-a-project
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
