version: 2.1
orbs:
  testlio: testlio/testlio@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  copy-sample-configs:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Copy sample config files
          command: |
            cp ./sample-config/* .
      - persist_to_workspace:
          root: .
          paths:
            - ./test-config.json
            - ./project-config.json

workflows:
  test-deploy:
    jobs:
      - copy-sample-configs:
          filters: *filters
      - testlio/schedule-run:
          dry-run: true
          test-args: "--spec tests/login-test.ts"
          filters: *filters
          requires:
            - copy-sample-configs
          attach-workspace: true
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: testlio/testlio
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - copy-sample-configs
            - testlio/schedule-run
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
