description: >
  This command packaging the test project.
parameters:
  dir:
    type: string
    description: "Select the path to test project sources."
  filename:
    type: string
    default: "test_package.zip"
    description: "Select the output package file name (default: test_package.zip)."
steps:
  - run:
      name: Create a test package
      environment:
        PROJECT_DIR: << parameters.dir >>
        PACKAGE_NAME: << parameters.filename >>
      command: << include(scripts/package.sh) >>
